global:
  scrape_interval: 10s

  external_labels:
    monitor: 'media_search' 

scrape_configs:
  - job_name: 'media_search'

    scrape_interval: 10s

    static_configs:
      - targets: ['localhost:9888', 'localhost:9988', 'localhost:9989']
